### ISSUE TITLE
python-pyflakes must be a string: flycheck-pyflakes-executable

### ISSUE THREAD

**Issue by cpaulik** [Wilfred/flycheck-pyflakes#3]
I get the same error as described at https://github.com/syl20bnr/spacemacs/issues/8583

It seems that `(stringp (car command))` does not evaluate to `t` [here](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L4590) if the variable is used.

```
(setq test '(flycheck-pyflakes-executable source-inplace))
(stringp (car test))
```
does evaluate to `nil` for me

**Comment by Wilfred** [comment]
Sorry about that! Fixed.

(I'm delighted this project has found some users -- I thought it was just me!)

**Comment by cpaulik** [comment]
Thanks, I use it daily.
